# reload config
bind=SUPER,r,reload_config
# exit mango
bind=SUPER,m,quit,

# menu and terminal
bind=SUPER,q,killclient,
bind=SUPER,F4,killclient,
bind=ALT,F4,killclient,
bind=SUPER,t,spawn,alacritty
bind=SUPER,n,spawn,alacritty -e nmtui
bind=SUPER,space,spawn,wofi --show run
bind=SUPER,e,spawn,thunar
bind=SUPER,comma,spawn,gucharmap
bind=SUPER,period,spawn,wofi-emoji
bind=SUPER,a,spawn,pavucontrol
bind=SUPER,l,spawn,swaylock -f -c 000000
bind=SUPER,v,spawn,clipman pick -t wofi

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=SUPER,u,focuslast
bind=SUPER,Up,focusdir,left
bind=SUPER,Down,focusdir,right

# swap window pos
bind=Super+Shift,Left,tagtoleft,0
bind=Super+Shift,Right,tagtoright,0
bind=Super+Shift,Up,exchange_client,left
bind=Super+Shift,Down,exchange_client,right

# switch window status
bind=ALT,Tab,toggleoverview,
bind=SUPER,backslash,togglefloating,
bind=Super,f,togglefullscreen,

# scroller layout
bind=ALT,z,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,

# tag switch
bind=Super,Left,viewtoleft_have_client,0
bind=Super,Right,viewtoright_have_client,0

# switch to tag number
bind=Super,0,view,0,0
bind=Super,1,view,1,0
bind=Super,2,view,2,0
bind=Super,3,view,3,0
bind=Super,4,view,4,0
bind=Super,5,view,5,0
bind=Super,6,view,6,0
bind=Super,7,view,7,0
bind=Super,8,view,8,0
bind=Super,9,view,9,0

# move window to tag number
bind=Super+Shift,0,tag,0,0
bind=Super+Shift,1,tag,1,0
bind=Super+Shift,2,tag,2,0
bind=Super+Shift,3,tag,3,0
bind=Super+Shift,4,tag,4,0
bind=Super+Shift,5,tag,5,0
bind=Super+Shift,6,tag,6,0
bind=Super+Shift,7,tag,7,0
bind=Super+Shift,8,tag,8,0
bind=Super+Shift,9,tag,9,0

# monitor switch
bind=alt+shift,Left,focusmon,left
bind=alt+shift,Right,focusmon,right
bind=alt+shift,Up,focusmon,up
bind=alt+shift,Down,focusmon,down

# Mouse Button Bindings
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# brightness and volume
bind=none,XF86AudioRaiseVolume,spawn_shell,notify-send -t 1000 -a ponymix "Volume" -h int:value:$(ponymix increase 5)
bind=none,XF86AudioLowerVolume,spawn_shell,notify-send -t 1000 -a ponymix "Volume" -h int:value:$(ponymix decrease 5)
bind=none,XF86AudioMute,spawn_shell,notify-send -t 1000 -a ponymix "Muted" -h int:value:$(ponymix toggle)
bind=none,XF86MonBrightnessUp,spawn_shell,brightnessctl s +10%
bind=none,XF86MonBrightnessDown,spawn_shell,brightnessctl s 10%-

#custom app bind
bind=None,Print,spawn_shell,grim -g "$(slurp -b '#2E2A1E55' -c '#fb751bff')" ~/Media/screenie/$(date +%s).png
bind=SUPER,h,spawn_shell,bash ~/.config/mango/scripts/hide_waybar.sh
bind=SUPER,z,spawn,shmooz
# bind=SUPER,z,spawn_shell,bash ~/.config/mango/scripts/toggle-zoom.sh
